//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberConversion
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="NumberConversion.NumberConversionSoapType")]
    public interface NumberConversionSoapType
    {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento NumberToWordsResult do namespace http://www.dataaccess.com/webservicesserver/ não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        NumberConversion.NumberToWordsResponse NumberToWords(NumberConversion.NumberToWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberConversion.NumberToWordsResponse> NumberToWordsAsync(NumberConversion.NumberToWordsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento NumberToDollarsResult do namespace http://www.dataaccess.com/webservicesserver/ não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        NumberConversion.NumberToDollarsResponse NumberToDollars(NumberConversion.NumberToDollarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberConversion.NumberToDollarsResponse> NumberToDollarsAsync(NumberConversion.NumberToDollarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NumberConversion.NumberToWordsRequestBody Body;
        
        public NumberToWordsRequest()
        {
        }
        
        public NumberToWordsRequest(NumberConversion.NumberToWordsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong ubiNum;
        
        public NumberToWordsRequestBody()
        {
        }
        
        public NumberToWordsRequestBody(ulong ubiNum)
        {
            this.ubiNum = ubiNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NumberConversion.NumberToWordsResponseBody Body;
        
        public NumberToWordsResponse()
        {
        }
        
        public NumberToWordsResponse(NumberConversion.NumberToWordsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToWordsResult;
        
        public NumberToWordsResponseBody()
        {
        }
        
        public NumberToWordsResponseBody(string NumberToWordsResult)
        {
            this.NumberToWordsResult = NumberToWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NumberConversion.NumberToDollarsRequestBody Body;
        
        public NumberToDollarsRequest()
        {
        }
        
        public NumberToDollarsRequest(NumberConversion.NumberToDollarsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal dNum;
        
        public NumberToDollarsRequestBody()
        {
        }
        
        public NumberToDollarsRequestBody(decimal dNum)
        {
            this.dNum = dNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public NumberConversion.NumberToDollarsResponseBody Body;
        
        public NumberToDollarsResponse()
        {
        }
        
        public NumberToDollarsResponse(NumberConversion.NumberToDollarsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToDollarsResult;
        
        public NumberToDollarsResponseBody()
        {
        }
        
        public NumberToDollarsResponseBody(string NumberToDollarsResult)
        {
            this.NumberToDollarsResult = NumberToDollarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface NumberConversionSoapTypeChannel : NumberConversion.NumberConversionSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<NumberConversion.NumberConversionSoapType>, NumberConversion.NumberConversionSoapType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NumberConversionSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(NumberConversionSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), NumberConversionSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberConversionSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NumberConversionSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberConversionSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NumberConversionSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NumberConversion.NumberToWordsResponse NumberConversion.NumberConversionSoapType.NumberToWords(NumberConversion.NumberToWordsRequest request)
        {
            return base.Channel.NumberToWords(request);
        }
        
        public string NumberToWords(ulong ubiNum)
        {
            NumberConversion.NumberToWordsRequest inValue = new NumberConversion.NumberToWordsRequest();
            inValue.Body = new NumberConversion.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            NumberConversion.NumberToWordsResponse retVal = ((NumberConversion.NumberConversionSoapType)(this)).NumberToWords(inValue);
            return retVal.Body.NumberToWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberConversion.NumberToWordsResponse> NumberConversion.NumberConversionSoapType.NumberToWordsAsync(NumberConversion.NumberToWordsRequest request)
        {
            return base.Channel.NumberToWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberConversion.NumberToWordsResponse> NumberToWordsAsync(ulong ubiNum)
        {
            NumberConversion.NumberToWordsRequest inValue = new NumberConversion.NumberToWordsRequest();
            inValue.Body = new NumberConversion.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            return ((NumberConversion.NumberConversionSoapType)(this)).NumberToWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NumberConversion.NumberToDollarsResponse NumberConversion.NumberConversionSoapType.NumberToDollars(NumberConversion.NumberToDollarsRequest request)
        {
            return base.Channel.NumberToDollars(request);
        }
        
        public string NumberToDollars(decimal dNum)
        {
            NumberConversion.NumberToDollarsRequest inValue = new NumberConversion.NumberToDollarsRequest();
            inValue.Body = new NumberConversion.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            NumberConversion.NumberToDollarsResponse retVal = ((NumberConversion.NumberConversionSoapType)(this)).NumberToDollars(inValue);
            return retVal.Body.NumberToDollarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberConversion.NumberToDollarsResponse> NumberConversion.NumberConversionSoapType.NumberToDollarsAsync(NumberConversion.NumberToDollarsRequest request)
        {
            return base.Channel.NumberToDollarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberConversion.NumberToDollarsResponse> NumberToDollarsAsync(decimal dNum)
        {
            NumberConversion.NumberToDollarsRequest inValue = new NumberConversion.NumberToDollarsRequest();
            inValue.Body = new NumberConversion.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            return ((NumberConversion.NumberConversionSoapType)(this)).NumberToDollarsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NumberConversionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NumberConversionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NumberConversionSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.dataaccess.com/webservicesserver/NumberConversion.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.NumberConversionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.dataaccess.com/webservicesserver/NumberConversion.wso");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NumberConversionSoap,
            
            NumberConversionSoap12,
        }
    }
}
